apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-pod
          image: nginx:1.13
          ports:
            - containerPort: 80

