apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: web-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-ctr
        image: httpd:2.4
        ports:
        - containerPort: 80

